import type { Metadata } from "next";
import { Space_Grotesk, Inter, BenchNine } from "next/font/google";
import "./globals.css";
import NavBar from "./sections/NavBar";
import Provider from "./Provider";
import Footer from "./sections/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-grotesk",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const benchNine = BenchNine({
  subsets: ["latin"],
  variable: "--font-bench-nine",
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${grotesk.variable} ${inter.variable} ${benchNine.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <Provider>
          <NavBar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
